GET http://localhost:3003/ping

###
GET http://localhost:3003/videos

###
GET http://localhost:3003

###
POST http://localhost:3003/videos
Content-Type: application/json

{
    "id": "testedelete",
    "title": "testando delete",
    "durSeconds": 100
}

###
PUT http://localhost:3003/videos/teste100
Content-Type: application/json

{
    "title": "testando edição usando business"
}


###

DELETE  http://localhost:3003/videos/testedelete