GET http://localhost:3003/ping

###
GET http://localhost:3003/videos

###
GET http://localhost:3003

###
POST http://localhost:3003/videos
Content-Type: application/json

{
    "id": "testerotas",
    "title": "testando rotas",
    "durSeconds": 100
}

###
PUT http://localhost:3003/videos/testerotas
Content-Type: application/json

{
    "title": "testando edição usando rotas"
}


###
DELETE  http://localhost:3003/videos/testerotasdeletar